services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost/api
    volumes:
      - ./frontend:/src/app
      - /src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/src:/var/www
    depends_on:
      - php
      - frontend
